### ISSUE TITLE
Code breaks when I upgrade my angular from 8.0 to 9.0 

### ISSUE THREAD

**Issue by ashismo** [lukasz-galka/ngx-gallery#309]
When I upgraded my angular from 8.0 to 9.0, getting the below error. Can you please fix this?
ERROR in node_modules/ngx-gallery/ngx-gallery-helper.service.d.ts:1:22 - error TS2724: Module '"node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
Can you please fix this?

**Comment by kolkov** [comment]
Hi! Try to use this version for Angular 8, 9.
 https://www.npmjs.com/package/@kolkov/ngx-gallery

**Comment by ashismo** [comment]
Thanks for your reply. I have used this and the same has been broken. Please see the below image. 
I have the below settings. Looks like the height is not working

this.galleryOptions = [
      {
          width: '100%',
          height: '300px',
          thumbnailsColumns: 4,
          imageAnimation: NgxGalleryAnimation.Slide,
          previewZoom: true,
          previewZoomMax: 4,
          previewZoomStep: 0.4,
          imageSwipe: true,
          previewRotate: true,
          imageDescription: true,
          fullscreenIcon: 'fas fa-compress',
          previewFullscreen: true,
          imageArrowsAutoHide: true,
          preview: true,
          actions: this.gallaryActions
      },
      // max-width 800
      {
          breakpoint: 800,
          width: '100%',
          height: '300px',
          imagePercent: 80,
          thumbnailsPercent: 20,
          thumbnailsMargin: 20,
          thumbnailMargin: 20,
          previewZoom: true,
          preview: true,
          actions: this.gallaryActions
      },
      // max-width 400
      {
          breakpoint: 400,
          width: '100%',
          height: '300px',
          fullWidth: true,
          imageDescription: true,
          preview: true,
          actions: this.gallaryActions
      }
    ];

![image](https://user-images.githubusercontent.com/11231867/78849109-8be71080-79e1-11ea-93b1-ea34de2ca7d2.png)

**Comment by cehager** [comment]
Hi! Try to use this version for Angular 8, 9.
https://www.npmjs.com/package/@kolkov/ngx-gallery

**Comment by kolkov** [comment]
> Thanks for your reply. I have used this and the same has been broken. Please see the below image.
> I have the below settings. Looks like the height is not working
> 
> this.galleryOptions = [
> {
> width: '100%',
> height: '300px',
> thumbnailsColumns: 4,
> imageAnimation: NgxGalleryAnimation.Slide,
> previewZoom: true,
> previewZoomMax: 4,
> previewZoomStep: 0.4,
> imageSwipe: true,
> previewRotate: true,
> imageDescription: true,
> fullscreenIcon: 'fas fa-compress',
> previewFullscreen: true,
> imageArrowsAutoHide: true,
> preview: true,
> actions: this.gallaryActions
> },
> // max-width 800
> {
> breakpoint: 800,
> width: '100%',
> height: '300px',
> imagePercent: 80,
> thumbnailsPercent: 20,
> thumbnailsMargin: 20,
> thumbnailMargin: 20,
> previewZoom: true,
> preview: true,
> actions: this.gallaryActions
> },
> // max-width 400
> {
> breakpoint: 400,
> width: '100%',
> height: '300px',
> fullWidth: true,
> imageDescription: true,
> preview: true,
> actions: this.gallaryActions
> }
> ];
> 
> ![image](https://user-images.githubusercontent.com/11231867/78849109-8be71080-79e1-11ea-93b1-ea34de2ca7d2.png)
Do you have this class?
https://github.com/kolkov/ngx-gallery/issues/8

**Comment by cehager** [comment]
Did you upgrade from this repository?
https://github.com/kolkov/ngx-gallery

It worked for me with angular 9.1.
Cheers

**Comment by saifansari2** [comment]
https://github.com/kolkov/ngx-gallery

this is not working with dynamic binding with api post response

static binding is working fine

**Comment by saifansari2** [comment]
it is not working with .webp format
